//! Worker process for AWS Lambda micro-VMs.
//!
//! Snapshot safety: Lambda snapshots this process after it starts and restores
//! that snapshot for every micro-VM. Nothing unique may be generated before the
//! `/run` hook fires: no random seeds, ids, secrets, or outbound connections
//! at startup. Anything of that kind belongs in `hooks::run`.

mod hooks;
mod state;
mod websocket;

use std::{net::SocketAddr, time::Duration};

use std::sync::Arc;

use axum::{Json, Router, extract::State, routing::get};
use serde_json::{Value, json};
use tokio::signal::unix::{SignalKind, signal};
use tracing::{info, warn};

use crate::state::{AppState, Lifecycle, MAX_CONNECTIONS, SharedState};

// Generated by prost from proto/worker.proto; its internals are not ours to name.
#[allow(clippy::min_ident_chars)]
pub mod proto {
    include!(concat!(env!("OUT_DIR"), "/worker.v1.rs"));
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env().unwrap_or_else(|_| "info".into()),
        )
        .init();

    // PORT is what dev proxies such as portless hand out; WS_ADDR is the
    // container and micro-VM setting. Both bind every interface so the
    // Lambda proxy or Docker port mapping can reach the process.
    let addr: SocketAddr = match std::env::var("PORT") {
        Ok(port) => format!("0.0.0.0:{port}").parse()?,
        Err(_) => std::env::var("WS_ADDR")
            .unwrap_or_else(|_| "0.0.0.0:8080".to_string())
            .parse()?,
    };

    let listener = tokio::net::TcpListener::bind(addr).await?;
    info!(%addr, "websocket server listening");

    let state = AppState::new();
    let app = Router::new()
        .route("/health", get(health))
        .route("/ws", get(websocket::handler))
        .nest(hooks::PREFIX, hooks::router())
        .with_state(Arc::clone(&state));

    axum::serve(
        listener,
        app.into_make_service_with_connect_info::<SocketAddr>(),
    )
    .with_graceful_shutdown(shutdown_signal(Arc::clone(&state)))
    .await?;

    Ok(())
}

#[allow(clippy::needless_pass_by_value)]
async fn health(State(state): State<SharedState>) -> Json<Value> {
    let microvm = state.microvm.read().await;
    Json(json!({
        "status": "ok",
        "microvmId": microvm.as_ref().map(|current| current.microvm_id.as_str()),
        "openConnections": state.open_connections(),
        "maxConnections": MAX_CONNECTIONS,
        "draining": state.is_draining(),
    }))
}

/// How long shutdown waits for clients to close before letting axum stop.
const SHUTDOWN_DRAIN: Duration = Duration::from_secs(3);

/// Resolves on Ctrl-C or SIGTERM, whichever comes first, after telling every
/// open connection to go away. Without that, axum's graceful shutdown would
/// wait on websockets that never finish on their own.
async fn shutdown_signal(state: SharedState) {
    let ctrl_c = async {
        if let Err(error) = tokio::signal::ctrl_c().await {
            warn!(%error, "failed to listen for ctrl-c");
        }
    };
    let terminate = async {
        match signal(SignalKind::terminate()) {
            Ok(mut sigterm) => {
                sigterm.recv().await;
            }
            Err(error) => warn!(%error, "failed to listen for SIGTERM"),
        }
    };
    tokio::select! {
        () = ctrl_c => {},
        () = terminate => {},
    }
    let remaining = state
        .drain_connections(Lifecycle::Terminate, SHUTDOWN_DRAIN)
        .await;
    info!(remaining, "shutdown signal received, connections drained");
}
